### ISSUE TITLE
Deploy to a WebApp Container from a private repo does not work

### ISSUE THREAD

**Issue by sarmadjari** [Azure/webapps-container-deploy#10]
the push to a private Azure repo working, but to deploy from the private repo to WebApp Container does not work.

**Comment by N-Usha** [comment]
Thanks for reporting the issue. Could you please use azure/webapps-deploy@v2 action in your workflow in place of azure/webapps-container-deploy and confirm if you are still seeing this issue?

**Comment by eaarora-ms** [comment]
Closing due to no response from the customer. Please comment to re-open.
