### ISSUE TITLE
Authentication for WebApp and WebApp containers

### ISSUE THREAD

**Issue by RoopeshNair** [Azure/webapps-container-deploy#2]
Service Principal has few overheads from getting started perspective. For example, the user needs permission to create AAD Application, permissions on the subscription or resource, permission to perform role assignments. Especially for GitHub developers this might be a long pole

For web apps action (non-container), we support publish profile based auth/ per-site credentials. 

This is issue is tracking purpose to evaluate if the authentication for webapp containers can be simplified further.

**Comment by N-Usha** [comment]
Closing this now as we now support both webapps & web app for containers using webapps-deploy action and publish profile
