### ISSUE TITLE
Action fails silently if web app is not setup for containers

### ISSUE THREAD

**Issue by hisuwh** [Azure/webapps-container-deploy#3]
I misunderstood how web app for containers worked and tried to deploy over an existing web app.  Looking at my actions it seemed to have worked: 

![image](https://user-images.githubusercontent.com/4470351/69824464-bdfe8f80-1203-11ea-8041-3dec85ffa214.png)

But in actuality, it had failed.  My only clue was this in the logs:
```
Could not parse response: ***
Response: undefined
```

**Comment by bijeebuss** [comment]
Im getting the same error. What did you have to do to set up your web app for containers?

**Comment by hisuwh** [comment]
My problem was that I had a regular web app deployed which was incompatible with Web Apps for containers deployment.

I can't remember whether I had to delete just the deployment or the entire wep app and start again.

**Comment by asranja** [comment]
Please reopen if still facing the issue.
