### ISSUE TITLE
How to deploy multiple docker image built by docker-compose into single instance?

### ISSUE THREAD

**Issue by mattdamon108** [Azure/webapps-container-deploy#7]
Hey team!

I'm very glad to use the github action for docker container build and deploy. I'm using docker-compose to run my web app which is consisting of one static react web app and one node app to prerender for SPA in each Dockerfile. I've made a workflow to build with docker-compose. But, I can't figure out to deploy the generated docker images into the single server instance in azure through github action workflow.

Is there any reference for my case?

**Comment by phifa** [comment]
@mattdamon108 any sucess?

**Comment by AmrutaKawade** [comment]
can you use https://github.com/Azure/webapps-deploy this github action? multi container deployment is supported in this. Check if this solves your problem

**Comment by AmrutaKawade** [comment]
Please try out other action. closing this issue.
