### ISSUE TITLE
"Azure Logout" step is not run if the action fails

### ISSUE THREAD

**Issue by darzu** [Azure/webapps-container-deploy#8]
![Screen Shot 2020-02-21 at 10 03 34 AM](https://user-images.githubusercontent.com/6453828/75059337-9b41e700-5491-11ea-872a-7a99445e2ade.png)

If the action fails part of the way through, the logout step is not run.
If the logout step is not necessary, it should be removed all together.
If it is necessary or adds security, then it should be made to always run regardless of the outcome. Like a finally {} block.

**Comment by N-Usha** [comment]
closing this issue as the enhancement is being tracked separately and will be implemented on Webapps-deploy action as this action will soon be archived.
