### ISSUE TITLE
 Run azure/webapps-container-deploy@v1 took 15 minutes with many 500s and failed attempts

### ISSUE THREAD

**Issue by darzu** [Azure/webapps-container-deploy#9]
![Screen Shot 2020-02-21 at 10 17 27 AM](https://user-images.githubusercontent.com/6453828/75060424-a85fd580-5493-11ea-9074-53adeb8bddfe.png)

Reading the log, it's not actually clear to me that it succeeded even though it shows green.

Here's the log:

> [PATCH]https://management.azure.com/subscriptions/<redacted>/resourceGroups/***/providers/Microsoft.Web/sites/mywebapp_redacted/config/web?api-version=2016-08-01
Updated App Service Configuration settings.
Restarting app service: mywebapp_redacted
[POST]https://management.azure.com/subscriptions/<redacted>/resourceGroups/***/providers/Microsoft.Web/sites/mywebapp_redacted/restart?api-version=2016-08-01
Restarted app service: mywebapp_redacted
[POST]https://management.azure.com/subscriptions/<redacted>/resourceGroups/***/providers/Microsoft.Web/sites/mywebapp_redacted/config/appsettings/list?api-version=2016-08-01
[PUT]***mywebapp_redacted.scm.azurewebsites.net/api/deployments/2b5011fd3706e5e9c7d2fa574671e8d0fe8f74431582307999581
[PUT]***mywebapp_redacted.scm.azurewebsites.net/api/deployments/2b5011fd3706e5e9c7d2fa574671e8d0fe8f74431582307999581
[PUT]***mywebapp_redacted.scm.azurewebsites.net/api/deployments/2b5011fd3706e5e9c7d2fa574671e8d0fe8f74431582307999581
Could not parse response: ***
Response: undefined
Encountered a retriable status code: 503. Message: 'Service Temporarily Unavailable'.
[PUT]***mywebapp_redacted.scm.azurewebsites.net/api/deployments/2b5011fd3706e5e9c7d2fa574671e8d0fe8f74431582307999581
Could not parse response: ***
Response: undefined
Encountered a retriable status code: 503. Message: 'Service Temporarily Unavailable'.
[PUT]***mywebapp_redacted.scm.azurewebsites.net/api/deployments/2b5011fd3706e5e9c7d2fa574671e8d0fe8f74431582307999581
Could not parse response: ***
Response: undefined
Encountered a retriable status code: 502. Message: 'Bad Gateway'.
[PUT]***mywebapp_redacted.scm.azurewebsites.net/api/deployments/2b5011fd3706e5e9c7d2fa574671e8d0fe8f74431582307999581
Successfully updated deployment History at https://mywebapp_redacted.scm.azurewebsites.net/api/deployments/2b5011fd3706e5e9c7d2fa574671e8d0fe8f74431582307999581
[POST]https://management.azure.com/subscriptions/<redacted>/resourceGroups/***/providers/Microsoft.Web/sites/mywebapp_redacted/publishxml?api-version=2016-08-01
Could not parse response: ***
Response: undefined
App Service Application URL: https://mywebapp_redacted.azurewebsites.net

**Comment by N-Usha** [comment]
Thanks for reporting the issue @darzu . Could you please use azure/webapps-deploy@v2 action in your workflow in place of azure/webapps-container-deploy and confirm if you are still seeing this issue?

**Comment by eaarora-ms** [comment]
Closing due to no response from the customer. Please comment to re-open.
